DELETE http://localhost:3001/api/blogs/620e7805351a2a0671af302e
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRva2EiLCJpZCI6IjYyMGU1ZWY5YmE5Y2YyYjUzOGJjZjE4NyIsImlhdCI6MTY0NTEyMDE3OH0.ZknfnmqINcSVhAYiJELQPmyYEfrJLb662e4AcvUKbqM