POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvbG1hcyIsImlkIjoiNjIwZTVmMjJlMDU5MDBjMjM3YzMxNTBlIiwiaWF0IjoxNjQ1MTI1NjQ3fQ.VFOLs2lO6fMy8pUQqMOXdGpnRO7TiY8b6Dh4NNUIhr8

{
    "title": "blogin lisäys tokenExtractorilla kolmannelle",
    "author": "asd",
    "url": "asd",
    "likes": 5
  }